version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: socialapp-db
    environment:
      POSTGRES_DB: socialapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vinter2026
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - socialapp-network

  app:
    build: .
    container_name: socialapp-backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/socialapp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: vinter2026
    ports:
      - "9091:9091"
    networks:
      - socialapp-network

volumes:
  postgres-data:

networks:
  socialapp-network:
